#!/usr/bin/env bash
# This script
start() {
    echo "manage_my_process started"
    ./manage_my_process &
    sudo bash -c "echo $! > /var/run/my_process.pid"
}

stop() {
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    sudo bash -c "rm /var/run/my_process.pid"
}

restart() {
    echo "manage_my_process restarted"
    kill "$(cat /var/run/my_process.pid)"
    sudo bash -c "rm /var/run/my_process.pid"
    ./manage_my_process &
    sudo bash -c "echo $! > /var/run/my_process.pid"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
	;;
esac

exit 0
