#!/usr/bin/env bash
# This script displays "bad luck" the 4th iteration, "good luck" the 8th, and "Holberton School" for the rest from 1 to 10
i=1
while [ $i -le 20 ]
do
    echo $i

    case $i in

	4)
	    echo "bad luck from China"
	    ;;

	8)
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo "bad luck from Italy"
	    ;;
    esac

    ((i++))
done
